repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: ^examples/
      - id: ruff-format
        exclude: ^examples/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or:
          [javascript, jsx, ts, tsx, json, yaml, css, scss, html, markdown]
        exclude: ^examples/

default_language_version:
  python: python3

exclude: |
  (?x)(
    ^.venv/|
    ^.git/|
    ^.pytest_cache/|
    ^agentweave.egg-info/
  )
